const observedAt = "2026-10-02T09:00:00+08:00";

export const product = Object.freeze({
  id: "product-ipad-a16",
  sku: "EDU-IPAD-A16-128-SLV",
  name: "11-inch tablet (A16)",
  variant: "128GB · Wi‑Fi · Silver",
  quantity: 1,
  category: "Study device",
  listPriceCents: 359900,
  dataLabel: "Demo SKU aligned to the PRD research case; not a live merchant listing",
});

export const user = Object.freeze({
  id: "demo-student-01",
  displayName: "Alex",
  studentStatus: "valid",
  credentialStatus: "active",
  credentialScope: "demo-merchant-student-offer",
  pointsBalance: 240,
});

export const paymentMethods = Object.freeze([
  {
    id: "mock-tap-go",
    name: "Tap & Go · Sandbox",
    kind: "Mock payment adapter",
    verified: true,
    feeUpperBoundCents: 0,
    notice: "No real wallet, card network or HKT API is connected.",
  },
  {
    id: "mock-campus-wallet",
    name: "Campus Wallet · Sandbox",
    kind: "Mock payment adapter",
    verified: true,
    feeUpperBoundCents: 0,
    notice: "Local simulator only; no money moves.",
  },
]);

export const offers = Object.freeze([
  {
    id: "EDU-200",
    version: "1.2",
    title: "Verified student price",
    kind: "product_discount",
    merchantId: "campus-demo-store",
    merchant: "Campus Demo Store",
    eligibility: "studentStatus=valid and credentialStatus=active",
    validFrom: "2026-09-01T00:00:00+08:00",
    validUntil: "2026-12-31T23:59:59+08:00",
    stackableWith: ["SHIP-0"],
    minimumSpendCents: 339900,
    valueCents: 20000,
    paymentRestrictions: ["mock-tap-go"],
    source: "CampusCart Sandbox Rule Registry",
    sourceUrl: null,
    observedAt,
    verificationStatus: "verified_demo",
    disclaimer: "Synthetic hackathon rule; not a real merchant offer.",
  },
  {
    id: "SHIP-0",
    version: "1.1",
    title: "Demo free standard delivery",
    kind: "shipping_waiver",
    merchantId: "campus-demo-store",
    eligibility: "standard delivery address in demo zone",
    validFrom: "2026-09-01T00:00:00+08:00",
    validUntil: "2026-12-31T23:59:59+08:00",
    stackableWith: ["EDU-200"],
    minimumSpendCents: 300000,
    valueCents: 16000,
    paymentRestrictions: ["mock-tap-go"],
    source: "CampusCart Sandbox Rule Registry",
    sourceUrl: null,
    observedAt,
    verificationStatus: "verified_demo",
    disclaimer: "Synthetic delivery waiver used to demonstrate re-verification.",
  },
  {
    id: "HT-STUDENT-100",
    version: "2.0",
    title: "Harbour student saving",
    kind: "product_discount",
    merchantId: "harbour-tech-sandbox",
    merchant: "Harbour Tech Sandbox",
    eligibility: "studentStatus=valid",
    validFrom: "2026-10-01T00:00:00+08:00",
    validUntil: "2026-11-30T23:59:59+08:00",
    stackableWith: ["CAMPUS-POINTS"],
    minimumSpendCents: 300000,
    valueCents: 10000,
    paymentRestrictions: ["mock-campus-wallet"],
    source: "CampusCart Sandbox Rule Registry",
    sourceUrl: null,
    observedAt,
    verificationStatus: "verified_demo",
    disclaimer: "Synthetic hackathon rule; not a real merchant offer.",
  },
  {
    id: "UM-VOUCHER-120",
    version: "1.0",
    title: "UniMall web voucher",
    kind: "product_discount",
    merchantId: "unimall-demo",
    merchant: "UniMall Demo",
    eligibility: "all demo users",
    validFrom: "2026-09-15T00:00:00+08:00",
    validUntil: "2026-10-31T23:59:59+08:00",
    stackableWith: [],
    minimumSpendCents: 350000,
    valueCents: 12000,
    paymentRestrictions: ["mock-tap-go"],
    source: "CampusCart Sandbox Rule Registry",
    sourceUrl: null,
    observedAt,
    verificationStatus: "verified_demo",
    disclaimer: "Synthetic hackathon rule; not a real merchant offer.",
  },
  {
    id: "MEGA-300-OLD",
    version: "0.8",
    title: "Archived mega voucher",
    kind: "product_discount",
    merchantId: "unimall-demo",
    merchant: "UniMall Demo",
    eligibility: "all demo users",
    validFrom: "2026-07-01T00:00:00+08:00",
    validUntil: "2026-08-31T23:59:59+08:00",
    stackableWith: [],
    minimumSpendCents: 300000,
    valueCents: 30000,
    paymentRestrictions: ["mock-tap-go"],
    source: "CampusCart Sandbox Historical Rules",
    sourceUrl: null,
    observedAt: "2026-08-31T18:00:00+08:00",
    verificationStatus: "expired",
    disclaimer: "Deliberately expired test rule.",
  },
]);

export const purchasePaths = Object.freeze([
  {
    id: "campus-delivery",
    merchantId: "campus-demo-store",
    merchant: "Campus Demo Store",
    channel: "Demo web checkout",
    sku: product.sku,
    productCents: 359900,
    shippingCents: 0,
    originalShippingCents: 16000,
    appliedOfferIds: ["EDU-200", "SHIP-0"],
    paymentMethodId: "mock-tap-go",
    points: null,
    rewardCents: 0,
    fulfillment: "Standard delivery · Sandbox promise",
  },
  {
    id: "harbour-points",
    merchantId: "harbour-tech-sandbox",
    merchant: "Harbour Tech Sandbox",
    channel: "Demo student portal",
    sku: product.sku,
    productCents: 354900,
    shippingCents: 3000,
    originalShippingCents: 3000,
    appliedOfferIds: ["HT-STUDENT-100"],
    paymentMethodId: "mock-campus-wallet",
    points: { ruleId: "CAMPUS-POINTS", maxPoints: 100, centsPerPoint: 50, redemptionStep: 20 },
    rewardCents: 0,
    fulfillment: "Campus pickup · 3–5 demo days",
  },
  {
    id: "unimall-reward",
    merchantId: "unimall-demo",
    merchant: "UniMall Demo",
    channel: "Demo web checkout",
    sku: product.sku,
    productCents: 359900,
    shippingCents: 0,
    originalShippingCents: 0,
    appliedOfferIds: ["UM-VOUCHER-120"],
    paymentMethodId: "mock-tap-go",
    points: null,
    rewardCents: 2000,
    fulfillment: "Store pickup · 2–4 demo days",
  },
]);

export function defaultPolicy(scenario = "success") {
  return {
    budgetCents: scenario === "blocked" ? 350000 : 360000,
    allowPoints: true,
    maxPoints: 100,
    acceptableMerchantIds: purchasePaths.map((path) => path.merchantId),
    autoPay: true,
    priceIncreaseRule: "reconfirm_any_increase",
    paymentMethodIds: paymentMethods.map((method) => method.id),
  };
}

export function publicSeed() {
  return { product, user, paymentMethods, offers, purchasePaths };
}
